ALTER TABLE aluno ADD COLUMN DATA_NASCIMENTO VARCHAR(10);

ALTER TABLE aluno RENAME COLUMN telefone TO contato;

ALTER TABLE aluno ALTER COLUMN contato VARCHAR(20);

ALTER TABLE livro ADD COLUMN ISBN BIGINT(13);

ALTER TABLE livro DROP COLUMN ISBN;